# Generated by Django 5.2.8 on 2025-11-18 09:01

import core.models.user
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Регион')),
                ('short_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Краткое имя')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', core.models.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код автомобиля')),
                ('vin', models.CharField(blank=True, default='', max_length=17, verbose_name='VIN')),
                ('state_number', models.CharField(max_length=20, verbose_name='Гос. номер')),
                ('model', models.CharField(max_length=100, verbose_name='Марка, модель')),
                ('manufacture_year', models.PositiveSmallIntegerField(default=2000, verbose_name='Год выпуска')),
                ('owner_inn', models.CharField(default='', max_length=17, verbose_name='ИНН владельца')),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='подразделение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('status', models.CharField(default='', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='core.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'db_table': 'cars',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('add_refuel', 'Добавление заправки'), ('view_report', 'Просмотр отчёта'), ('access_denied', 'Отказ в доступе'), ('error', 'Ошибка'), ('info', 'Информация')], max_length=50, verbose_name='Действие')),
                ('details', models.TextField(blank=True, verbose_name='Подробности')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Системный лог',
                'verbose_name_plural': 'Системные логи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Зона')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('regions', models.ManyToManyField(related_name='zones', to='core.region', verbose_name='Регионы')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
                'db_table': 'zones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.zone', verbose_name='Зона'),
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Количество литров')),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Бензин'), ('DIESEL', 'Дизель')], default='GASOLINE', max_length=20, verbose_name='Тип топлива')),
                ('filled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заправки')),
                ('source', models.CharField(choices=[('CARD', 'Топливная карта'), ('TGBOT', 'Телеграм-бот'), ('TRUCK', 'Топливозаправщик')], default='TGBOT', max_length=50, verbose_name='Способ заправки')),
                ('approved', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('historical_department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подразделение (на момент заправки)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='core.car', verbose_name='Автомобиль')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_records', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник (заправщик)')),
                ('historical_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region', verbose_name='Регион (на момент заправки)')),
            ],
            options={
                'verbose_name': 'Запись о заправке',
                'verbose_name_plural': 'Заправки',
                'db_table': 'fuel_records',
                'ordering': ['-filled_at'],
                'indexes': [models.Index(fields=['filled_at'], name='fuel_record_filled__0f7eb5_idx'), models.Index(fields=['approved'], name='fuel_record_approve_99ad49_idx'), models.Index(fields=['car', 'filled_at'], name='fuel_record_car_id_d4a2fc_idx'), models.Index(fields=['source', 'filled_at'], name='fuel_record_source_081ac2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('liters__gt', 0)), name='positive_liters')],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['code'], name='cars_code_88ef46_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['state_number'], name='cars_state_n_db41ea_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_active', 'status'], name='cars_is_acti_93673c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id'], name='users_telegra_d76140_idx'),
        ),
    ]
