# Generated by Django 5.2.8 on 2025-11-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
