"""
Django settings for nextbot project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from environs import Env
from pathlib import Path


env = Env()
env.read_env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", "Replace me")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", True)


ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", ["127.0.0.1", "localhost"], delimiter=",")


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'ninja',
    
    # My apps
    'core',    
]

AUTH_USER_MODEL = "core.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nextbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nextbot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Telegram
TELEGRAM_BOT_TOKEN = env.str("TELEGRAM_BOT_TOKEN", "")

# 1С:Элемент API настройки
ELEMENT_API_URL = env.str("ELEMENT_API_URL", "https://1c.0nalog.com:1710/Transavto/hs/")
ELEMENT_API_USER = env.str("ELEMENT_API_USER", "")
ELEMENT_API_PASSWORD = env.str("ELEMENT_API_PASSWORD", "")

# Google API настройки
GSHEET_CREDENTIALS_JSON_PATH=BASE_DIR / env.str("GSHEET_CREDENTIALS_JSON_PATH", "")
GSHEET_SPREADSHEET_ID=env.str("GSHEET_SPREADSHEET_ID", "")
GSHEET_SHEET_NAME=env.str("GSHEET_SHEET_NAME", "")

# Расписание синхронизации
SYNC_CARS_SCHEDULE_MINUTES = env.int("SYNC_CARS_SCHEDULE_MINUTES", 30)

# Глобальные обработчики ошибок
CSRF_FAILURE_VIEW = "django.views.csrf.csrf_failure"

# Необязательно, но улучшает UX
LOGIN_URL = "/admin/login/?next=/admin/"

# === Настройки логирования ===

# где будут храниться логи
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "your_email@gmail.com"
# EMAIL_HOST_PASSWORD = "your_password"
# SERVER_EMAIL = EMAIL_HOST_USER
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ADMINS = [("Admin", "admin@example.com")]  # кто получит письма об ошибках

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} [{name}:{lineno}] {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname}: {message}",
            "style": "{",
        },
    },

    "handlers": {
        # Консоль (для локальной разработки и Docker)
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        
        # Лог-файл всего проекта с ротацией по размеру
        "file_general": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "project.log",
            "maxBytes": 10 * 1024 * 1024,  # 10 MB
            "backupCount": 5,  # хранить 5 backup файлов
            "formatter": "verbose",
            "level": "INFO",
            "encoding": "utf-8",
        },
        
        # Отдельный файл для ошибок с ротацией по дням
        "file_errors": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOG_DIR / "errors.log",
            "when": "midnight",  # ротация каждый день в полночь
            "interval": 1,  # каждый день
            "backupCount": 30,  # хранить 30 дней логов
            "formatter": "verbose",
            "level": "ERROR",
            "encoding": "utf-8",
        },
        
        # Файл для SQL запросов с ограничением по размеру
        "file_sql": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "sql.log",
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 3,  # хранить 3 backup файла
            "formatter": "verbose",
            "level": "DEBUG",
            "encoding": "utf-8",
        },
        
        # Письма администраторам (только в продакшене)
        "mail_admins": {
            "class": "django.utils.log.AdminEmailHandler",
            "level": "ERROR",
            "formatter": "verbose",
        },
    },

    "root": {
        "handlers": ["console", "file_general", "file_errors"],
        "level": "INFO",
    },

    "loggers": {
        # Основной логгер Django
        "django": {
            "handlers": ["console", "file_general"],
            "level": "INFO",
            "propagate": True,
        },

        # Ошибки безопасности
        "django.security": {
            "handlers": ["file_errors"],
            "level": "WARNING",
            "propagate": False,
        },

        # Логгер запросов (404, 500)
        "django.request": {
            "handlers": ["file_errors", "mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },

        # Логгер ORM (SQL-запросы) - теперь в отдельный файл
        "django.db.backends": {
            "handlers": ["file_sql"],
            "level": "DEBUG",  # DEBUG для просмотра SQL
            "propagate": False,
        },

        # Telegram-бот
        "core.bot": {
            "handlers": ["console", "file_general"],
            "level": "INFO",
            "propagate": False,
        },

        # Пользовательские ошибки
        "nextbot.custom": {
            "handlers": ["console", "file_errors"],
            "level": "WARNING",
            "propagate": False,
        },
        
        # Логгер для синхронизации с 1С
        "core.clients": {
            "handlers": ["console", "file_general"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Настройки логирования в продакшене
if not DEBUG:
    LOGGING["handlers"]["console"]["level"] = "WARNING"  # меньше шума в консоли
    LOGGING["root"]["handlers"] = ["file_general", "file_errors", "mail_admins"]
    
    # Увеличиваем ограничения
    LOGGING["handlers"]["file_general"]["maxBytes"] = 100 * 1024 * 1024  # 100 MB
    LOGGING["handlers"]["file_general"]["backupCount"] = 10  # 10 файлов
    LOGGING["handlers"]["file_errors"]["backupCount"] = 180  # 6 месяцев
    